import { Colors } from "@/constants/theme";
import { NotificationItem, useNotificationsStore } from "@/store/notifications";
import React, { useMemo, useRef } from "react";
import {
  FlatList,
  ListRenderItem,
  Pressable,
  Text,
  View,
  ViewToken,
} from "react-native";

export default function InboxScreen() {
  const notifications = useNotificationsStore((s) => s.notifications);
  const markRead = useNotificationsStore((s) => s.markRead);

  const viewabilityConfig = useMemo(
    () => ({ itemVisiblePercentThreshold: 60 }),
    []
  );

  const onViewableItemsChanged = useRef(
    ({ viewableItems }: { viewableItems: ViewToken[] }) => {
      for (const v of viewableItems) {
        const item = v.item as NotificationItem | undefined;
        if (item && !item.read) {
          markRead(item.id);
        }
      }
    }
  );

  const renderItem: ListRenderItem<NotificationItem> = ({ item }) => (
    /*
    * TODO: This UI is not correct. It was generated by GitHub Copilot. 
    * We needs to redesign it.
    */

    <Pressable
      onPress={() => !item.read && markRead(item.id)}
      style={{
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: item.read ? "#fff" : "#fef3f2",
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
      }}
    >
      <Text
        style={{
          fontWeight: item.read ? "400" : "700",
          color: Colors["light"].text,
          marginBottom: 4,
        }}
        numberOfLines={1}
      >
        {item.title || "Notification"}
      </Text>
      {!!item.message && (
        <Text style={{ color: "#667085" }} numberOfLines={2}>
          {item.message}
        </Text>
      )}
      {!!item.pushedDate && (
        <Text style={{ color: "#98A2B3", marginTop: 6, fontSize: 12 }}>
          {new Date(item.pushedDate).toLocaleString()}
        </Text>
      )}
    </Pressable>

    /*
    * TODO: This UI is not correct. It was generated by GitHub Copilot. 
    * We needs to redesign it.
    */
  );

  return (
    <View style={{ flex: 1, backgroundColor: "#fff" }}>
      <FlatList
        data={notifications}
        keyExtractor={(item) => String(item.id)}
        renderItem={renderItem}
        onViewableItemsChanged={onViewableItemsChanged.current}
        viewabilityConfig={viewabilityConfig}
        contentContainerStyle={{ paddingBottom: 16 }}
        ListEmptyComponent={() => (
          <View style={{ padding: 24 }}>
            <Text style={{ color: "#667085" }}>No notifications</Text>
          </View>
        )}
      />
    </View>
  );
}
